authentication_app/urls.py
from django.urls import path
from . import views

app_name = 'authentication_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('self_verification/', views.self_verification, name='self_verification'),
    path('password_reset/<str:user_id>/<str:token>/', views.password_reset, name='password_reset'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
]

e_voting_13/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication_app.urls')),
    path('root/', include('root_app.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root_app/urls.py
from django.urls import path
from . import views

app_name = 'root_app'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_user/', views.add_user, name='add_user'),
    path('users/', views.users, name='users'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('edit_user/<str:user_id>/', views.edit_user, name='edit_user'),
    path('view_user/<str:user_id>/', views.view_user, name='view_user'),
    path('group/', views.group, name='group'),
    path('edit_group/<str:group_id>/', views.group, name='group'),
    path('groups/', views.groups, name='groups'),
    path('delete_group/', views.delete_group, name='delete_group'),
    path('group_permissions/<str:group_id>/', views.group_permissions, name='group_permissions'),
    path('search_permissions/', views.search_permissions, name='search_permissions'),
    path('programme/', views.programme, name='programme'),
    path('edit_programme/<str:programme_id>/', views.programme, name='programme'),
    path('programmes/', views.programmes, name='programmes'),
    path('delete_programme/', views.delete_programme, name='delete_programme'),
    path('permissible_page/', views.permissible_page, name='permissible_page'),
    path('year_class/', views.year_class, name='year_class'),
    path('edit_year_class/<str:class_id>/', views.year_class, name='year_class'),
    path('classes/', views.classes, name='classes'),
    path('delete_class/', views.delete_class, name='delete_class'),
    path('hall/', views.hall, name='hall'),
    path('edit_hall/<str:hall_id>/', views.hall, name='hall'),
    path('halls/', views.halls, name='halls'),
    path('delete_hall/', views.delete_hall, name='delete_hall'),
    path('polling_station/', views.polling_station, name='polling_station'),
    path('edit_pollingstation/<str:station_id>/', views.polling_station, name='polling_station'),
    path('polling_stations/', views.polling_stations, name='polling_stations'),
    path('delete_pollingstation/', views.delete_pollingstation, name='delete_pollingstation'), 
    path('election/', views.election, name='election'), 
    path('elections/', views.elections, name='elections'), 
    path('edit_election/<str:election_id>/', views.edit_election, name='edit_election'), 
    path('delete_election/', views.delete_election, name='delete_election'), 
    path('add_electorate/', views.add_electorate, name='add_electorate'),
    path('get_class/', views.get_class, name='get_class'), 
    path('electorates/', views.electorates, name='electorates'), 
    path('edit_electorate/<str:electorate_id>/', views.edit_electorate, name='edit_electorate'),     
    path('electorate_excelupload/', views.electorate_excelupload, name='electorate_excelupload'),     
    path('get_excel_data/', views.get_excel_data, name='get_excel_data'),     
    path('delete_electorate/', views.delete_electorate, name='delete_electorate'),     
    path('delete_bulkelectorates/', views.delete_bulkelectorates, name='delete_bulkelectorates'),     
    path('position/', views.position, name='position'),     
    path('edit_position/<str:position_id>/', views.position, name='position'),     
    path('positions/', views.positions, name='positions'),     
    path('delete_position/', views.delete_position, name='delete_position'),     
    path('position_filter/', views.position_filter, name='position_filter'),     
    path('add_aspirant/', views.add_aspirant, name='add_aspirant'),     
    path('filter_ballotnumber/', views.filter_ballotnumber, name='filter_ballotnumber'),     
    path('aspirants/', views.aspirants, name='aspirants'),     
    path('edit_aspirant/<str:aspirant_id>/', views.edit_aspirant, name='edit_aspirant'),     
    path('delete_aspirant/', views.delete_aspirant, name='delete_aspirant'),     
    path('view_aspirant/', views.view_aspirant, name='view_aspirant'),     
    path('filter_aspirant/', views.filter_aspirant, name='filter_aspirant'),     
    path('election_results/', views.election_results, name='election_results'),     
    path('verification/', views.verification, name='verification'),     
    path('verified_electorates/', views.verified_electorates, name='verified_electorates'),     
    path('unverify_electorate/', views.unverify_electorate, name='unverify_electorate'),     
    path('getting_totalaspirants/', views.getting_totalaspirants, name='getting_totalaspirants'),     
    path('voting_ballot/', views.voting_ballot, name='voting_ballot'),     
    path('set_currentelection/', views.set_currentelection, name='set_currentelection'),     
    path('get_selected_aspirants/', views.get_selected_aspirants, name='get_selected_aspirants'),     
    path('cast_vote/', views.cast_vote, name='cast_vote'),     
    path('results/<str:election_id>/', views.results, name='results'),     
    path('get_results/<str:election_id>/', views.get_results, name='get_results'),     
    path('print_results/<str:election_id>/', views.print_results, name='print_results'),     
    path('detailed_report/', views.detailed_report, name='detailed_report'),     
    path('send_password_link/', views.send_password_link, name='send_password_link'),     
    path('general_report/', views.general_report, name='general_report'),     
    path('institution_info/', views.institution_info, name='institution_info'),     
]

root_app/models.py
from django.db import models
from authentication_app.models import User
from datetime import datetime

class Programme(models.Model):

    programme_name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Programmes'
    
    def __str__(self) -> str:
        return self.programme_name

class YearClass(models.Model):

    year = models.PositiveIntegerField()
    class_name = models.CharField(max_length=50)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Classes'
    
    def __str__(self):
        return self.year

    # def class_programmes(self):
    #     pros = YearClass.objects.filter(programme=self.programme)

    #     return pros

class Hall(models.Model):

    hall_name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Halls'
    
    def __str__(self):
        return self.hall_name

class PollingStation(models.Model):

    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    @property
    def is_alreadyallowed(self):
        if AllowedPollingStation.objects.filter(polling_station_id=self.id).exists():
            return True
        return False

    class Meta:
        verbose_name_plural = 'Polling Stations'

    def __str__(self):
        return self.name

class Election(models.Model):

    election_name = models.CharField(max_length=100)
    election_year = models.PositiveIntegerField(null=True, blank=False)
    election_date = models.DateField()
    election_time = models.TimeField()
    ending_date = models.DateField()
    ending_time = models.TimeField()
    allow_multiple_votes = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    time_stamp = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name_plural = 'Elections'

        ordering = ['-time_stamp']

        permissions = [
            ('can_assign_commnissioner_role', 'Can assign commissioner role'),
            ('view_results', 'Can view results'),
            ('view_election_results_list', 'Can view election results list'),
            ('view_general_report', 'Can view general report'),
            ('view_detailed_report', 'Can view detailed report'),
            ('set_currentelection', 'Can set current election')
        ]
    
    def __str__(self):
        return self.election_name
    
    @property
    def is_open(self):
        s_date = str(self.election_date) + " " + str(self.election_time)
        e_date = str(self.ending_date) + " " + str(self.ending_time)

        if str(datetime.now()) >= e_date or str(datetime.now()) < s_date or not self.is_active:
            return False
        else:
            return True
    
    @property
    def electoral_comm(self):

        election = Election.objects.get(id=self.id)
        return election.electoralcommissioner.user.full_name
            


class ElectoralCommissioner(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    election = models.OneToOneField(Election, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Electoral Commissioner'

        permissions= [
            ('verify_electorate', 'Can verify electorate')
        ]

        ordering = ['election']
    
    def __str__(self):
        return self.user.full_name

class CurrentElection(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    set_by = models.ForeignKey(User, on_delete=models.CASCADE)
    time_stamp = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.election.election_name

    
    class Meta:
        verbose_name_plural = 'Current Elections'

class AllowedPollingStation(models.Model):

    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    polling_station = models.ForeignKey(PollingStation, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Allowed Polling Stations'
    

    def __str__(self) -> str:
        return self.election.election_name + " - " + self.polling_station.name

class Position(models.Model):

    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    position_name = models.CharField(max_length=50)
    position_description = models.TextField()
    number_of_asp = models.PositiveIntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Positions'
    

    def __str__(self):
        return self.position_name
    
    @property
    def total_vote_count(self):

        current_eleaction = CurrentElection.objects.all().last()

        total = Vote.objects.filter(position=Position.objects.get(id=self.id), election=current_eleaction.election).count()

        return total
    
    @property
    def turnout_percentage(self):

        try:

            current_election = CurrentElection.objects.all().last()

            election = Election.objects.get(id=current_election.election.id)

            total = 0

            for data in election.allowedpollingstation_set.all():
                total += ElectorateProfile.objects.filter(polling_station=data.polling_station).count()

            # users = User.objects.all()

            # filtered_users = []

            # for data in users:
            #     if data.user_type == 'user':
            #         filtered_users.append(data)
            
            percentage = (self.total_vote_count / total) * 100

            return round(percentage, 2)
        
        except Exception:
            return ''


class Aspirant(models.Model):

    passport_picture = models.ImageField(upload_to='aspirant_pictures')
    first_name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    other_name = models.CharField(max_length=100)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    ballot_number = models.PositiveIntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)


    @property
    def full_name(self):
        if self.other_name is not None:
            return f'{self.first_name} {self.other_name} {self.surname}'
        else:
            return f'{self.first_name} {self.surname}'

    class Meta:

        verbose_name_plural = 'Aspirants'

        ordering = ['ballot_number']

        permissions = [
            ('can_view_aspirants', 'Can view aspirants')
        ]
    
    def __str__(self) -> str:
        return self.full_name
    
    @property
    def aspirant_vote_counts(self):
        total = Vote.objects.filter(aspirant_id=self.id).count()

        return total

    @property
    def aspirant_vote_percentage(self):
        try:
            percentage = (self.aspirant_vote_counts / self.position.total_vote_count) * 100 

            return round(percentage, 2)
        
        except Exception:
            return ''


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    aspirant = models.ForeignKey(Aspirant, on_delete=models.CASCADE)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = [
            ('can_view_result', 'Can View Result'),
            ('print_results', 'Can Print Result'),
        ]

        verbose_name_plural = 'Votes'
    
    def __str__(self):
        return self.user.first_name + " " + self.aspirant.first_name


class ElectorateProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)
    polling_station = models.ForeignKey(PollingStation, on_delete=models.CASCADE)
    year_class = models.ForeignKey(YearClass, on_delete=models.CASCADE)

    class Meta:

        verbose_name_plural = 'Electorate Profiles'

        permissions = [
            ('add_electorate', 'Can add electorate'),
            ('delete_electorate', 'Can delete electorate'),
            ('change_electorate', 'Can change electorate'),
            ('view_electorate', 'Can view electorate'),
            ('upload_electorate_with_excel', 'Can upload electorate with excel')
        ]
    
    def __str__(self):
        return self.user.full_name



class VerifiedElectorate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    verified_by = models.ForeignKey(User, related_name="VerifiedVoters", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Verified Electorates'

        permissions = [
            ('view_verified_electorates', 'Can view verifed electorates'),
            ('unverify_electorates', 'Can unverify electorates')
        ]

    
    def __str__(self) -> str:
        return self.user.full_name

class InstitutionInfo(models.Model):
    logo = models.ImageField(upload_to='company_logo')
    name = models.CharField(max_length=200)
    abv_name = models.CharField(max_length=10)
    email = models.EmailField()
    phone = models.TextField(max_length=10)
    description = models.TextField()

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name_plural = ['Institution Info']

root_app/templates/root_app/aspirants.html
{% extends 'root_app/base.html' %}

{% load static %}

{% block title %} Aaspirants/Candidates {% endblock %}

{% block header %} Aaspirants/Candidates  {% endblock %}


{% block content %}

<div class="content-wrapper">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Aaspirants/Candidates </h4>

            {% csrf_token %}

            <div class="row mb-3">
                <div class="col-sm-2">
                    <label class="form-label">FILTER: </label>
                </div>
                <div class="col-sm-5">

                    {% csrf_token %}

                    <select name="election" id="election" class="form-control">
                        <option value="">Choose Election</option>

                        {% if perms.root_app.add_election and user.user_type != 'superuser' and not perms.root_app.can_assign_commnissioner_role %}
                            {% for data in user.electoralcommissioner_set.all %}
                                    <option value="{{data.election.id}}">{{data.election.election_name}}</option>
                            {% endfor %}
                        {% else %}
                            {% for data in elections %}
                                    <option value="{{data.id}}">{{data.election_name}}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="col-sm-5">
                    <select id="position" class="form-control">
                        <option value=""> Choose Position</option>
                    </select>
                </div>
            </div>
            <p class="card-description">
                All Candidates
            </p>
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="dataTable">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Full name</th>
                            <th>Election</th>
                            <th>Position</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    
                    <tbody id="list-body">

                        {% if perms.root_app.add_election and user.user_type != 'superuser' and not perms.root_app.can_assign_commnissioner_role %}

                            {% for data in aspirants %}

                                {% if data.election.electoralcommissioner.user.id == user.id %}
                                    <tr id="aspirant{{data.id}}">
                                        <td> <img src="{{data.passport_picture.url}}" alt=""> </td>
                                        <td>{{data.full_name}}</td>
                                        <td>{{data.election.election_name}}</td>
                                        <td>{{data.position.position_name}}</td>
                                        <td>
                                            <input type="hidden" value="{{data.id}}">
                                            {% csrf_token %}

                                            {% if perms.root_app.view_aspirant %}
                                                <button class="btn btn-sm btn-info view-asp"><i class="mdi mdi-eye"></i> </button>
                                            {% endif %}

                                            {% if perms.root_app.change_aspirant %}
                                            <a href="{% url 'root_app:edit_aspirant' data.id %}" class="btn btn-sm btn-primary">Edit <i class="mdi mdi-pencil"></i> </a>
                                            {% endif %}

                                            {% if perms.root_app.delete_aspirant %}
                                            <button class="btn btn-sm btn-danger delete-aspirant"> <i class="mdi mdi-delete"></i> </button>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endif %}

                            {% endfor %}
                        
                        {% else %}
                            {% for data in aspirants %}
                                
                                <tr id="aspirant{{data.id}}">
                                    {% csrf_token %}
                                    <td> <img src="{{data.passport_picture.url}}" alt=""> </td>
                                    <td>{{data.full_name}}</td>
                                    <td>{{data.election.election_name}}</td>
                                    <td>{{data.position.position_name}}</td>
                                    <td>
                                        <input type="hidden" value="{{data.id}}">
                                        {% csrf_token %}

                                        {% if perms.root_app.view_aspirant %}
                                            <button class="btn btn-sm btn-info view-asp"><i class="mdi mdi-eye"></i> </button>
                                        {% endif %}

                                        {% if perms.root_app.change_aspirant %}
                                        <a href="{% url 'root_app:edit_aspirant' data.id %}" class="btn btn-sm btn-primary">Edit <i class="mdi mdi-pencil"></i> </a>
                                        {% endif %}

                                        {% if perms.root_app.delete_aspirant %}
                                        <button class="btn btn-sm btn-danger delete-aspirant"> <i class="mdi mdi-delete"></i> </button>
                                        {% endif %}
                                    </td>
                                </tr>

                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>


    <div class="modal fade" id="view-asp-modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Aspirant's Detail</h5>
                </div>
                <div class="modal-body">
                    <img src="" alt="" class="mb-3" style="margin: auto; width: 100%;" id="photo">
                    <table class="table table-striped" id="table-view">
            
                    </table>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'root_app/scripts/add-aspirant.js' %}"></script>
    <script src="{% static 'root_app/scripts/filter-aspirant.js' %}"></script>
    <script src="{% static 'root_app/scripts/delete-aspirant.js' %}"></script>
    <script src="{% static 'root_app/scripts/view-aspirant.js' %}"></script>
{% endblock %}

root_app/templates/root_app/dashboard.html
{% extends 'root_app/base.html' %}

{% load static %}

{% block title %} Dashboard {% endblock %}

{% block header %} Dashboard {% endblock %}


{% block content %}

<div class="content-wrapper">

  {% if perms.authentication_app.view_dashboard %}

    <div class="row">
      <div class="col-sm-12 grid-margin stretch-card">

        {%  csrf_token %}

        <select id="election" class="form-control">
            <option value="">------------------All Elections--------------------</option>

            {% if perms.root_app.add_election and user.user_type != 'superuser' and not perms.root_app.can_assign_commnissioner_role %}
                {% for data in user.electoralcommissioner_set.all %}
                  {% if forloop.counter == 1 %}
                        <option value="{{data.election.id}}" selected>{{data.election.election_name}}</option>
                  {% else %}
                        <option value="{{data.election.id}}">{{data.election.election_name}}</option>
                  {% endif %}
                {% endfor %}
            {% else %}
                {% for data in elections %}
         
                    <option value="{{data.id}}"> {{data.election_name}}</option>
                  
                {% endfor %}
            {% endif %}
        </select>
      </div>
    </div>

    <div class="row">

      <div class="col-md-4 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
              <div>
                <p class="mb-2 text-md-center text-lg-left">Total Elections</p>
                <h1 class="mb-0">{{total_elections}}</h1>
              </div>
              <i class="mdi mdi-poll icon-xl text-secondary"></i>
            </div>
            <canvas id="balance-chart" height="80"></canvas>
          </div>
        </div>
      </div>

      <div class="col-md-4 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
              <div>
                <p class="mb-2 text-md-center text-lg-left">Total Electorates</p>
                <h1 class="mb-0">{{electorates_total}}</h1>
              </div>
              <i class="typcn typcn-user icon-xl text-secondary"></i>
            </div>
            <canvas id="expense-chart" height="80"></canvas>
          </div>
        </div>
      </div>
      
      <div class="col-md-4 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
              <div>
                <p class="mb-2 text-md-center text-lg-left">Total Aspirants</p>
                <h1 class="mb-0" id="t-asp-var">{{total_aspirants}}</h1>
              </div>
              <i class="typcn typcn-chart-pie icon-xl text-secondary"></i>
            </div>
            <canvas id="budget-chart" height="80"></canvas>
          </div>
        </div>
      </div>

    </div>

    {% if perms.authentication_app.view_dashboard_users %}

    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="table-responsive pt-3">
              <table class="table table-striped project-orders-table">
                <thead>
                  <tr>
                    <th class="ml-5">Username</th>
                    <th>Full name</th>
                    <th>Date added</th>
                    <th>Last login</th>
                    <th>User type</th>
                    <th>Email</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for data in users %}
                  <tr>
                    <td>{{data.username}}</td>
                    <td>{{data.full_name}}</td>
                    <td>{{data.date_added}}</td>
                    <td>{{data.last_login}}</td>
                    <td>{{data.user_type}}</td>
                    <td title="{{data.email}}">{{data.email|truncatechars:5}}</td>
                    <td>
                      <div class="d-flex align-items-center">
                        {% if perms.root_app.change_user %}
                        <a href="{% url 'root_app:edit_user' data.id %}" class="btn btn-success btn-sm btn-icon-text mr-3">
                          Edit
                          <i class="typcn typcn-edit btn-icon-append"></i>                          
                        </a>
                        {% endif %}
  
                        {% if perms.root_app.view_user %}
                        <a href="{% url 'root_app:view_user' data.id %}" class="btn btn-info btn-sm btn-icon-text">
                          View
                          <i class="mdi mdi-eye"></i>                          
                        </a>
                        {% endif %}
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endif %}
  
  {% else %}
    <div class="row">
      <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                    <tr>
                        <td>Current Election: </td>
                        <td> {{current_election.election.election_name}} </td>
                    </tr>
                    <tr>
                        <td>Election Time: </td>
                        <td>{{current_election.election.election_date}} {{current_election.election.election_time}}</td>
                    </tr>
    
                    <tr>
                        <td>Ending Time: </td>
                        <td>{{current_election.election.ending_date}} {{current_election.election.ending_time}}</td>
                    </tr>
                </table>
            </div>
            </div>
          </div>
      </div>
    </div>
  {% endif %}

  </div>

{% endblock %}


{% block scripts %}
    <script src="{% static 'root_app/scripts/aspirant_total_fil.js' %}"></script>
{% endblock %}

root_app/templates/root_app/programmes.html
{% extends 'root_app/base.html' %}

{% load static %}

{% block title %} Programmes {% endblock %}

{% block header %} Programmes {% endblock %}


{% block content %}

<div class="content-wrapper">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Programmes</h4>
            <p class="card-description">
                All programmes
            </p>
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="dataTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Programme</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        {% for data in programmes %}
                        <tr id="pro{{data.id}}">
                            <td>{{forloop.counter}}</td>
                            <td>{{data.programme_name}}</td>
                            <td>
                                <input type="hidden" value="{{data.id}}">
                                {% csrf_token %}

                                {% if perms.root_app.change_programme %}
                                    <a href="{% url 'root_app:programme' data.id %}" class="btn btn-sm btn-primary"> Edit <i class="mdi mdi-pencil"></i></a>
                                {% endif %}

                                {% if perms.root_app.delete_programme %}
                                    <button class="btn btn-sm btn-danger delete-programme"><i class="mdi mdi-delete"></i></button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'root_app/scripts/delete-programme.js' %}"></script>
{% endblock %}