authentication_app/urls.py
from django.urls import path
from . import views

app_name = 'authentication_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('self_verification/', views.self_verification, name='self_verification'),
    path('password_reset/<str:user_id>/<str:token>/', views.password_reset, name='password_reset'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
]

e_voting_13/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication_app.urls')),
    path('root/', include('root_app.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root_app/urls.py
from django.urls import path
from . import views

app_name = 'root_app'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_user/', views.add_user, name='add_user'),
    path('users/', views.users, name='users'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('edit_user/<str:user_id>/', views.edit_user, name='edit_user'),
    path('view_user/<str:user_id>/', views.view_user, name='view_user'),
    path('group/', views.group, name='group'),
    path('edit_group/<str:group_id>/', views.group, name='group'),
    path('groups/', views.groups, name='groups'),
    path('delete_group/', views.delete_group, name='delete_group'),
    path('group_permissions/<str:group_id>/', views.group_permissions, name='group_permissions'),
    path('search_permissions/', views.search_permissions, name='search_permissions'),
    path('programme/', views.programme, name='programme'),
    path('edit_programme/<str:programme_id>/', views.programme, name='programme'),
    path('programmes/', views.programmes, name='programmes'),
    path('delete_programme/', views.delete_programme, name='delete_programme'),
    path('permissible_page/', views.permissible_page, name='permissible_page'),
    path('year_class/', views.year_class, name='year_class'),
    path('edit_year_class/<str:class_id>/', views.year_class, name='year_class'),
    path('classes/', views.classes, name='classes'),
    path('delete_class/', views.delete_class, name='delete_class'),
    path('hall/', views.hall, name='hall'),
    path('edit_hall/<str:hall_id>/', views.hall, name='hall'),
    path('halls/', views.halls, name='halls'),
    path('delete_hall/', views.delete_hall, name='delete_hall'),
    path('polling_station/', views.polling_station, name='polling_station'),
    path('edit_pollingstation/<str:station_id>/', views.polling_station, name='polling_station'),
    path('polling_stations/', views.polling_stations, name='polling_stations'),
    path('delete_pollingstation/', views.delete_pollingstation, name='delete_pollingstation'), 
    path('election/', views.election, name='election'), 
    path('elections/', views.elections, name='elections'), 
    path('edit_election/<str:election_id>/', views.edit_election, name='edit_election'), 
    path('delete_election/', views.delete_election, name='delete_election'), 
    path('add_electorate/', views.add_electorate, name='add_electorate'),
    path('get_class/', views.get_class, name='get_class'), 
    path('electorates/', views.electorates, name='electorates'), 
    path('edit_electorate/<str:electorate_id>/', views.edit_electorate, name='edit_electorate'),     
    path('electorate_excelupload/', views.electorate_excelupload, name='electorate_excelupload'),     
    path('get_excel_data/', views.get_excel_data, name='get_excel_data'),     
    path('delete_electorate/', views.delete_electorate, name='delete_electorate'),     
    path('delete_bulkelectorates/', views.delete_bulkelectorates, name='delete_bulkelectorates'),     
    path('position/', views.position, name='position'),     
    path('edit_position/<str:position_id>/', views.position, name='position'),     
    path('positions/', views.positions, name='positions'),     
    path('delete_position/', views.delete_position, name='delete_position'),     
    path('position_filter/', views.position_filter, name='position_filter'),     
    path('add_aspirant/', views.add_aspirant, name='add_aspirant'),     
    path('filter_ballotnumber/', views.filter_ballotnumber, name='filter_ballotnumber'),     
    path('aspirants/', views.aspirants, name='aspirants'),     
    path('edit_aspirant/<str:aspirant_id>/', views.edit_aspirant, name='edit_aspirant'),     
    path('delete_aspirant/', views.delete_aspirant, name='delete_aspirant'),     
    path('view_aspirant/', views.view_aspirant, name='view_aspirant'),     
    path('filter_aspirant/', views.filter_aspirant, name='filter_aspirant'),     
    path('election_results/', views.election_results, name='election_results'),     
    path('verification/', views.verification, name='verification'),     
    path('verified_electorates/', views.verified_electorates, name='verified_electorates'),     
    path('unverify_electorate/', views.unverify_electorate, name='unverify_electorate'),     
    path('getting_totalaspirants/', views.getting_totalaspirants, name='getting_totalaspirants'),     
    path('voting_ballot/', views.voting_ballot, name='voting_ballot'),     
    path('set_currentelection/', views.set_currentelection, name='set_currentelection'),     
    path('get_selected_aspirants/', views.get_selected_aspirants, name='get_selected_aspirants'),     
    path('cast_vote/', views.cast_vote, name='cast_vote'),     
    path('results/<str:election_id>/', views.results, name='results'),     
    path('get_results/<str:election_id>/', views.get_results, name='get_results'),     
    path('print_results/<str:election_id>/', views.print_results, name='print_results'),     
    path('detailed_report/', views.detailed_report, name='detailed_report'),     
    path('send_password_link/', views.send_password_link, name='send_password_link'),     
    path('general_report/', views.general_report, name='general_report'),     
    path('institution_info/', views.institution_info, name='institution_info'),     
]

authentication_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager

class UserManager(UserManager):

    def create_user(self, username, email, phone_number, first_name, last_name, other_name=None, password=None, is_active=True, is_staff=False, is_superuser=False):

        if not username:
            raise ValueError('Username is required')
        if not email:
            raise ValueError('Email is required')
        if not phone_number:
            raise ValueError('Phone number is required')
        if password is None:
            raise ValueError('Password is required')
        
        user = self.model(
            email=self.normalize_email(email)
        )
        user.first_name=first_name
        user.last_name=last_name
        user.other_name=other_name
        user.username=username
        user.phone_number=phone_number
        user.active=is_active
        user.staff=is_staff
        user.superuser=is_superuser
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_superuser(self, email, username, phone_number, first_name, last_name, other_name=None, password=None, is_active=True, is_staff=True, is_superuser=True):

        user = self.create_user(
            email=email,
            username=username,
            phone_number=phone_number,
            first_name=first_name,
            last_name=last_name,
            other_name=other_name,
            is_active=is_active,
            is_staff=is_staff,
            is_superuser=is_superuser,
            password=password
        )

        return user
    
    def create_staffuser(self, username, email, phone_number, first_name, last_name, other_name=None, password=None, is_active=True, is_superuser=False, is_staff=True):

        user = self.create_user(
            username=username,
            email=email,
            phone_number=phone_number,
            first_name=first_name,
            last_name=last_name,
            other_name=other_name,
            password=password,
            is_active=is_active,
            is_staff=is_staff,
            is_superuser=is_superuser
        )

        return user

class User(AbstractUser):

    username = models.CharField(max_length=200, unique=True)
    email = models.EmailField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    other_name = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=15, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    superuser = models.BooleanField(default=False)
    time_stamp = models.DateTimeField(auto_now_add=True)


    @property
    def full_name(self):
        if self.other_name is not None:
            return f'{self.first_name} {self.other_name} {self.last_name}'
        else:
            return f'{self.first_name} {self.last_name}'
    
    @property
    def user_type(self):
        if self.staff and not self.superuser:
            return 'staff'
        elif self.staff and self.superuser:
            return 'superuser'
        else:
            return 'user'
    
    @property
    def is_active(self):
        return self.active

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', 'phone_number']

    
    class Meta:

        permissions = [
            ('view_users', 'Can view users'),
            ('assign_group', 'Can assign group to users'),
            ('assign_permission', 'Can assign permission to users'),
            ('view_dashboard', 'Can view dashboard'),
            ('view_dashboard_users', 'Can view dashboard current users on dashboard'),
        ]

        verbose_name_plural = 'Users'

    objects = UserManager()

    @property
    def is_active(self):
        return self.active
    
    @property
    def is_staff(self):
        return self.staff
    
    @property
    def is_superuser(self):
        return self.superuser

authentication_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from authentication_app.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from root_app.models import VerifiedElectorate, Vote, CurrentElection
from e_voting_13.random_password import generate_password
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from root_app.tokens import account_activation_token
from django.contrib import messages
from root_app.emails import send_password_resetlink
from e_voting_13.sms import mnotify
from django.contrib.sites.shortcuts import get_current_site


def login(request):

    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']

        next_url = request.GET.get('next')

        user = authenticate(username=username, password=password)

        if user is not None:

            if not user.is_active:
                return JsonResponse({'code':400, 'message':'Your account is inactive, contact admin'})

            if user.user_type == 'superuser':
                request.session['member_id'] = user.id
                auth.login(request, user)

                if next_url:
                    return JsonResponse({'code':200, 'url':next_url})
                
                return JsonResponse({'code':200, 'url':reverse('root_app:dashboard')})
            
            elif user.user_type == 'staff':
                request.session['member_id'] = user.id
                auth.login(request, user)

                if next_url:
                    return JsonResponse({'code':200, 'url':next_url})

                return JsonResponse({'code':200, 'url':reverse('root_app:dashboard')})
            
            elif user.user_type == 'user':

                if CurrentElection.objects.all().last():
                    current_election = CurrentElection.objects.all().last()

                    if not VerifiedElectorate.objects.filter(user=user, election=current_election.election).exists():
                        return JsonResponse({'code':400, 'message':'You are not verified'})
                    
                    # elif Vote.objects.filter(user=user, election=current_election.election):
                    #     return JsonResponse({'code':400, 'message':'You have voted already'})


                request.session['member_id'] = user.id
                auth.login(request, user)

                if next_url:
                    return JsonResponse({'code':200, 'url':next_url})

                return JsonResponse({'code':200, 'url':reverse('root_app:voting_ballot')})

        else:
            return JsonResponse({'code':400, 'message':'Invalid username or password, try again.'})
        
    else:
        return render(request, 'authentication_app/login.html')

def logout(request):

    messages.info(request, 'You have logged out successfully')

    auth.logout(request)
    try:
        del request.session['member_id']
    except KeyError:
        pass
    return redirect('authentication_app:login')

def self_verification(request):

    if request.method == 'POST':
        username = request.POST['username']

        password = generate_password(5)

        protocol = 'https://' if request.is_secure() else 'http://'

        url = reverse('authentication_app:login')

        message = f'#OTP: {password}. Visit {protocol}{get_current_site(request).domain}{url} to start voting.'

        if username == '':
            return JsonResponse({'code':400, 'message':'Enter a Username or Email'})

        if User.objects.filter(username=username).exists() or User.objects.filter(email=username).exists():
            if User.objects.filter(username=username).exists():
                user = User.objects.get(username=username)
            
            elif User.objects.filter(email=username).exists():
                user = User.objects.get(email=username)

            if user.user_type == 'user':
                user.set_password(password)
                user.save()

                if mnotify('', 'toskybrown', user.phone_number, message):
                    
                    messages.info(request, f'Your code has been sent successfully either into your email or your phone, use that as your password to log in')

                    return JsonResponse({'code':200, 'message':'Code sent successfully', 'url':reverse('authentication_app:login')})
                return JsonResponse({'code':400, 'message':'Something went wrong, try again.'})
            
            else:
                return JsonResponse({'code':400, 'message':'User not exist as Electorate'})
        else:
            return JsonResponse({'code':400, 'message':'Username or Email do not exist'})
    
    return render(request, 'authentication_app/self_verification.html')


def password_reset(request, user_id, token):

    print(force_str(urlsafe_base64_decode(user_id)))

    
    user = get_object_or_404(User, pk=force_str(urlsafe_base64_decode(user_id)))

    if request.method == 'POST':
        new_password = request.POST['password']
        con_password = request.POST['con_password']

        if not new_password:
            return JsonResponse({'code':400, 'message':'New password field required'})

        if new_password != con_password:
            return JsonResponse({'code':400, 'message':'Passwords donot match'})
        user.set_password(new_password)
        user.save()

        messages.info(request, "Password changed successfully")
        return JsonResponse({'code':200, 'message':'Password changed successfully', 'url':reverse('authentication_app:login')})
    
    if not user and account_activation_token.check_token(user, token):
        return HttpResponse('Invalid URL')
    context = {
        'uid':user_id,
        'token':token
    }
    return render(request, 'authentication_app/password_reset.html', context)


def forgot_password(request):

    if request.method == 'POST':
        username = request.POST['username']

        if not username:
            return JsonResponse({'code':400, 'message':'Enter username or email'})

        if User.objects.filter(username=username).exists():
            
            user = User.objects.get(username=username)
        
        elif User.objects.filter(email=username).exists():

            user = User.objects.get(email=username)

        else:
            return JsonResponse({'code':400, 'message':'The email or username you entered does not exist'})
        
        if user.user_type == 'user':
            return JsonResponse({'code':400, 'message':'You are not authorized to permform this action'})

        if send_password_resetlink(request, user, user.email):
            return JsonResponse({'code':200, 'message':f'A password reset link sent to {user.email} to into your inbox to change your password'})
        else:
            return JsonResponse({'code':200, 'message':'Something went wrong, try again. Contact administrator if problem persist.'})

    return render(request, 'authentication_app/forgot_password.html')

authentication_app/templates/authentication_app/forgot_password.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static %}

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Forgot password</title>
  <!-- base:css -->
  <link rel="stylesheet" href="{% static 'root_app/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'root_app/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{institution.logo.url}}" />
  <link rel="stylesheet" href="{% static 'root_app/alert_toaster_css/sweetalert/sweetalert.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/alert_toaster_css/toastr/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/fonts/materialdesigniconswebfont.svg' %}">

</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <h4 class="text-success">{{institution.name.upper}}</h4>
              </div>
              <h6 class="font-weight-light text-center">Enter your username or email to receive your password reset link</h6>
              

              <form class="pt-3" id="forgot-password" action="{% url 'authentication_app:forgot_password' %}">

                {% csrf_token %}

                <div class="form-group">
                  <input type="text" class="form-control form-control-lg" id="username" name="username" placeholder="Username or Email">
                </div>

                <div class="mt-3">
                  <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-bold auth-form-btn" id="login-button">
                    CONTINUE
                  </button>
                </div>

                <div class="mt-3 text-center">
                    <a href="{% url 'authentication_app:login' %}" class="auth-link" title="For only electorates">Back to Login</a>
                  </div>

                <div class="mt-3 text-center">
                  <hr class="mt-3">
                  <span class="text-muted">toskybrown Technologies</span>
                </div>
              
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

<script src="{% static 'root_app/jquery-3.7.1.min.js' %}"></script>

<!-- base:js -->
<script src="{% static 'root_app/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->

<!-- inject:js -->
<script src="{% static 'root_app/js/template.js' %}"></script>

<!-- endinject -->
<script src="{% static 'root_app/alert_toaster_js/toastr/toastr.min.js' %}"></script>
<script src="{% static 'root_app/alert_toaster_js/sweetalert/sweetalert.min.js' %}"></script>

<script src="{% static 'authentication_app/forgot-password.js' %}"></script>


</body>

</html>

authentication_app/templates/authentication_app/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static %}

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Authentication | Login</title>
  <!-- base:css -->
  <link rel="stylesheet" href="{% static 'root_app/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'root_app/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{institution.logo.url}}" />
  <link rel="stylesheet" href="{% static 'root_app/alert_toaster_css/sweetalert/sweetalert.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/alert_toaster_css/toastr/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/fonts/materialdesigniconswebfont.svg' %}">

</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <h4 class="text-success">{{institution.name.upper}}</h4>
              </div>
              <h6 class="font-weight-light text-center">Sign in to continue.</h6>
              
              {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success!</strong> {{message}}.
                <i class="mdi mdi-close text-lg-right" data-dismiss="alert" aria-label="Close" style="cursor: pointer;"></i>
              </div>
              {% endfor %}

              <form class="pt-3" id="login" action="{% url 'authentication_app:login' %}">

                {% csrf_token %}

                <div class="form-group">
                  <input type="text" class="form-control form-control-lg" id="username" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control form-control-lg" id="password" name="password" placeholder="Password">
                </div>

                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" name="keep_me" class="form-check-input">
                      Keep me signed in
                    </label>
                  </div>
                  <a href="{% url 'authentication_app:forgot_password' %}" class="auth-link text-black">Forgot password?</a>
                </div>
                
                <div class="mt-3">
                  <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-bold auth-form-btn" id="login-button">
                    SIGN IN
                  </button>
                </div>


                <div class="mt-3 text-center">
                  <a href="{% url 'authentication_app:self_verification' %}" class="auth-link" title="For only electorates">Self Verifaction</a>
                </div>

                <div class="mt-3 text-center">
                  <hr class="mt-3">
                  <span class="text-muted">toskybrown Technologies</span>
                </div>
              
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

<script src="{% static 'root_app/jquery-3.7.1.min.js' %}"></script>

<!-- base:js -->
<script src="{% static 'root_app/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->

<!-- inject:js -->
<script src="{% static 'root_app/js/template.js' %}"></script>

<!-- endinject -->
<script src="{% static 'authentication_app/login.js' %}"></script>
<script src="{% static 'root_app/alert_toaster_js/toastr/toastr.min.js' %}"></script>
<script src="{% static 'root_app/alert_toaster_js/sweetalert/sweetalert.min.js' %}"></script>

</body>

</html>

authentication_app/templates/authentication_app/password_reset.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static %}

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Password Recovery</title>
  <!-- base:css -->
  <link rel="stylesheet" href="{% static 'root_app/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'root_app/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{institution.logo.url}}" />
  <link rel="stylesheet" href="{% static 'root_app/alert_toaster_css/toastr/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'root_app/vendors/mdi/fonts/materialdesigniconswebfont.svg' %}">

</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <h4 class="text-success">{{institution.name.upper}}</h4>
              </div>
              <h6 class="font-weight-light text-center">PASSWORD RECOVERY</h6>
        

              <form class="pt-3" id="password-reset" action="{% url 'authentication_app:password_reset' uid token %}">

                {% csrf_token %}

                <div class="form-group">
                  <input type="password" class="form-control form-control-lg" id="password" name="password" placeholder="New password">
                </div>
                
                <div class="form-group">
                    <input type="password" class="form-control form-control-lg" id="con-password" name="con_password" placeholder="Confirm password">
                  </div>

                <div class="mt-3">
                  <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-bold auth-form-btn" id="reset-button">
                    CHANGE PASSWORD
                  </button>
                </div>

                <div class="mt-3 text-center">
                  <hr class="mt-3">
                  <span class="text-muted">toskybrown Technologies</span>
                </div>
              
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

<script src="{% static 'root_app/jquery-3.7.1.min.js' %}"></script>

<!-- base:js -->
<script src="{% static 'root_app/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->

<!-- inject:js -->
<script src="{% static 'root_app/js/template.js' %}"></script>

<script src="{% static 'authentication_app/password-reset.js' %}"></script>


<!-- endinject -->
<script src="{% static 'root_app/alert_toaster_js/toastr/toastr.min.js' %}"></script>

</body>

</html>